### PR TITLE
Fix double tap zoom scale for long from side to side photo.

### PR DESCRIPTION
**Pull request by yukitoto**
Current max scale of double tap is too large.
I modify max scale smaller like Facebook and Twitter by maximumDoubleTapZoomScale.

### CODE REVIEW

**Comment by yukitoto** [comment]
https://github.com/ideaismobile/IDMPhotoBrowser/issues/214

**Comment by yukitoto** [comment]
@eduardocallado what do you think about this update?

**Comment by eduardocallado** [comment]
This seems to be the correct way, and should be the default. Thanks for the fix!

**Comment by yukitoto** [comment]
@eduardocallado Thank you for your prompt response!

**Pull request merged**
