### PR TITLE
Use SDWebImage instead of AFNetworking

### PR DESCRIPTION
**Pull request by satococoa**
With SDWebImage, you can...

- support Animated GIF
- support WebP format
- and more... (https://github.com/rs/SDWebImage)

### CODE REVIEW

**Comment by tromg** [comment]
+1

**Comment by hfdiao** [comment]
+1

**Comment by mythodeia** [comment]
for anyone interested i just traded AFNetworking with SDWebImage (latest 3.7.1) in my fork
https://github.com/mythodeia/IDMPhotoBrowser

**Comment by rad182** [comment]
+1

**Comment by isaced** [comment]
+1 for SDWebImage

**Comment by satococoa** [comment]
thank you :yum:

**Pull request merged**
